name: Version Bump

on: [delete]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    permissions:
      actions: write
    steps:
      - name: Get auth token to push to ${{ inputs.sandbox }}
        id: version-bump
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.VERSION_BUMP_APP_ID }}
          private_key: ${{ secrets.VERSION_BUMP_APP_PRIVATE_KEY }}
          scope: arajkumar
      - name: Trigger Version Bump workflow
        run: |
         curl -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ steps.version-bump.outputs.token }}" \
            --request POST \
            https://api.github.com/repos/arajkumar/syncbot/actions/workflows/update-cmo-deps-versions.yaml/dispatches -d '{"ref":"main"}'
